imports:
  - { resource: parameters.yaml }

services:
  Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer:
    class: Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer
  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
  Symfony\Component\Serializer\Encoder\JsonEncoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
  Symfony\Component\Serializer\Serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - ['@Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer']
      - ['@Symfony\Component\Serializer\Encoder\JsonEncoder']
  Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface:
    class: 'Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface'
    factory: ['HelloFresh\Infrastructure\Security\Authentication\Provider\InMemoryAuthenticationProviderFactory', 'build']
    public: true
  Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface:
    class: 'Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
    factory: ['HelloFresh\Infrastructure\Security\Authentication\Token\TokenStorageFactory', 'build']
    public: true
  PDO:
    class: \PDO
    factory: ['HelloFresh\Infrastructure\Database\PDOConnectionFactory', 'build']
    arguments:
      - 'pgsql'
      - '%application.database.name%'
      - '%application.database.host%'
      - '%application.database.user%'
      - '%application.database.password%'
      - '%application.database.schema%'
  HelloFresh\Infrastructure\Repository\PostgresRecipeRepository:
    class: HelloFresh\Infrastructure\Repository\PostgresRecipeRepository
    arguments:
      - '@PDO'
  HelloFresh\Domain\Service\RecipeService:
    class: HelloFresh\Domain\Service\RecipeService
    arguments:
      - '@HelloFresh\Infrastructure\Repository\PostgresRecipeRepository'
  League\Tactician\CommandBus:
    class: League\Tactician\CommandBus
    factory: ['HelloFresh\Infrastructure\CommandBus\TacticianCommandBusFactory', 'build']
    arguments:
      - '@HelloFresh\Domain\Service\RecipeService'
  HelloFresh\Application\Controller\CreateRecipe:
    class: HelloFresh\Application\Controller\CreateRecipe
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
      - '@Symfony\Component\Serializer\Serializer'
      - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
  HelloFresh\Application\Controller\ListRecipes:
    class: HelloFresh\Application\Controller\ListRecipes
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
      - '@Symfony\Component\Serializer\Serializer'
  HelloFresh\Application\Controller\ReadRecipe:
    class: HelloFresh\Application\Controller\ReadRecipe
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
      - '@Symfony\Component\Serializer\Serializer'
  HelloFresh\Application\Controller\UpdateRecipe:
    class: HelloFresh\Application\Controller\UpdateRecipe
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
      - '@Symfony\Component\Serializer\Serializer'
      - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
  HelloFresh\Application\Controller\DeleteRecipe:
    class: HelloFresh\Application\Controller\DeleteRecipe
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
  HelloFresh\Application\Controller\RateRecipe:
    class: HelloFresh\Application\Controller\RateRecipe
    public: true
    arguments:
      - '@League\Tactician\CommandBus'
      - '@Symfony\Component\Serializer\Serializer'
